In [73]:
import pandas as pd
import numpy as np
np.random.seed(1234567)

In [74]:
E1 = [0,0,1,1]
E2 = [0,1,0,1]
saida = [0.0,1.0,1.0,0.0]
tx = 0.0001
erro_inicial = 0.0
I0 = np.zeros(4)
O0 = np.zeros(4)
I1 = np.zeros(4)
O1 = np.zeros(4)
I2 = np.zeros(2)
O2 = np.zeros(2)
w1 = np.random.rand(4,4)
w2 = np.random.rand(4,2)
nw1 = np.zeros((4,4))
nw2 = np.zeros((4,2))
vw1 = np.zeros((4,4))
vw2 = np.zeros((4,2))
d2 = 0.0
d1 = np.zeros(3)

In [75]:
def manipular_peso_trash_hold(matriz):
  if matriz.shape[0] == 2:
    for i in range(matriz.shape[0]):
      for j in range(matriz.shape[1]):
        matriz[i][j] =  (matriz[i][j]*40) -20 
  else:
    for i in range(matriz.shape[0]):
      matriz[i] = (matriz[i]*40)-20

In [76]:
manipular_peso_trash_hold(w1)
manipular_peso_trash_hold(w2)

In [77]:
erro = 1.0
m = 0.0
while erro > tx:
  erro = 0.0
  for x in range(101):
    cs= np.random.randint(3, size=1)
    I0[1] = E1[cs[0]]
    I0[2] = E2[cs[0]]
    I0[3] = 1.0
    O0[1]=I0[1]
    O0[2]=I0[2]
    O0[3]=I0[3]
    I1[1] = O0[1]*w1[1][1]+O0[2]*w1[2][1]+O0[3]*w1[3][1]
    I1[2] = O0[1]*w1[1][2]+O0[2]*w1[2][2]+O0[3]*w1[3][2]
    I1[3] = 1.0
    O1[1]=1.0/(1.0+np.exp(-I1[1]))
    O1[2]=1.0/(1.0+np.exp(-I1[2]))
    O1[3]=I1[3]
    I2[1]=O1[1]*w2[1][1]+O1[2]*w2[2][1]+O1[3]*w2[3][1]
    O2[1]=1.0/(1.0+np.exp(-I2[1]))


    d2=(saida[cs[0]]-O2[1])*O2[1]*(1.0-O2[1])
    d1[1]=O1[1]*(1.0-O1[1])*d2*w2[1][1]
    d1[2]=O1[2]*(1.0-O1[2])*d2*w2[2][1]
    nw2[1][1]= w2[1][1]+0.5*d2*O1[1]+0.5*vw2[1][1]
    vw2[1][1]=nw2[1][1]-w2[1][1]
    w2[1][1]=nw2[1][1]
    nw2[2][1]= w2[2][1]+0.5*d2*O1[2]+0.5*vw2[2][1]
    vw2[2][1]=nw2[2][1]-w2[2][1]
    w2[2][1]=nw2[2][1]
    nw2[3][1]= w2[3][1]+0.5*d2*O1[3]+0.5*vw2[3][1]
    vw2[3][1]=nw2[3][1]-w2[3][1]
    w2[3][1]=nw2[3][1]
    nw1[1][1]= w1[1][1]+0.5*d1[1]*O0[1]+0.5*vw1[1][1]
    vw1[1][1]=nw1[1][1]-w1[1][1]
    w1[1][1]=nw1[1][1]
    nw1[2][1]= w1[2][1]+0.5*d1[1]*O0[2]+0.5*vw1[2][1]
    vw1[2][1]=nw1[2][1]-w1[2][1]
    w1[2][1]=nw1[2][1]
    nw1[3][1]= w1[3][1]+0.5*d1[1]*O0[3]+0.5*vw1[3][1]
    vw1[3][1]=nw1[3][1]-w1[3][1]
    w1[3][1]=nw1[3][1]
    nw1[1][2]= w1[1][2]+0.5*d1[2]*O0[1]+0.5*vw1[1][2]
    vw1[1][2]=nw1[1][2]-w1[1][2]
    w1[1][2]=nw1[1][2]
    nw1[2][2]= w1[2][2]+0.5*d1[2]*O0[2]+0.5*vw1[2][2]
    vw1[2][2]=nw1[2][2]-w1[2][2]
    w1[2][2]=nw1[2][2]
    nw1[3][2]= w1[3][2]+0.5*d1[2]*O0[3]+0.5*vw1[3][2]
    vw1[3][2]=nw1[3][2]-w1[3][2]
    w1[3][2]=nw1[3][2]
    erro+= (saida[cs[0]]-O2[1])*(saida[cs[0]]-O2[1])
  erro = erro/100.0
  m+=1
  print(m,erro)

1.0 0.3199500881409586
2.0 0.3199497127507929
3.0 0.399936604199526
4.0 0.40993438783708364
5.0 0.3699402290760229
6.0 0.2899527746024798
7.0 0.3299458513246671
8.0 0.319947069023362
9.0 0.27995333835356895
10.0 0.37993614770390577
11.0 0.3299440487481056
12.0 0.2999487235782549
13.0 0.2999483272178651
14.0 0.4099287286704634
15.0 0.3699350207865417
16.0 0.3099450666927035
17.0 0.27994998921669456
18.0 0.359935148175352
19.0 0.2899472939118112
20.0 0.21995973609609795
21.0 0.2499539480892234
22.0 0.3999256523152259
23.0 0.38992670575989896
24.0 0.27994687476968755
25.0 0.25995028812305476
26.0 0.38992473311558223
27.0 0.39992191104335795
28.0 0.30993884472541483
29.0 0.2899422768874232
30.0 0.3599276468805918
31.0 0.3399309351672891
32.0 0.3199343379622914
33.0 0.3399295189404862
34.0 0.35992455425075226
35.0 0.3299300816393789
36.0 0.44990346629945405
37.0 0.309932672829377
38.0 0.30993198659480625
39.0 0.2799379670751128
40.0 0.37991488051887506
41.0 0.2899343000416739
42.0 0.2999313

In [78]:
print(w1)
print(w2)

[[-10.51883326 -19.69406505 -19.20678767  -7.47629525]
 [-16.02181343 -12.19400979 -11.70809238 -13.40275235]
 [  8.47515834 -18.71733415 -12.10522955  18.58227822]
 [  2.95578314   7.97962416  18.98562932   6.1740189 ]]
[[ -9.56526942 -12.14361604]
 [ 14.45853288  -9.69338674]
 [ -5.24658076  -2.79524346]
 [  7.31194155   8.40325892]]
