In [ ]:
import numpy as np
import pandas as pd
df = pd.DataFrame()
df_1 = pd.DataFrame()
df_2 = pd.DataFrame()
np.random.seed(123456)
KT = 1.0

In [ ]:
E1 = [0,0,1,1]
E2 = [0,1,0,1]
saida = [0.0,1.0,1.0,0.0]
tx = 0.0001
erro_inicial = 0.0
B = 10

In [ ]:
def manipular_peso_trash_hold(matriz):
  if matriz.shape[0] == 2:
    for i in range(matriz.shape[0]):
      for j in range(matriz.shape[1]):
        matriz[i][j] =  (matriz[i][j]*40) -20 
  else:
    for i in range(matriz.shape[0]):
      matriz[i] = (matriz[i]*40)-20

In [ ]:
def passo(matriz):
  matriz_1 =  np.random.rand(2,3)
  matriz_2 = np.random.rand(3)
  peso = np.random.rand(1)
  #print(matriz)
  if matriz.shape[0] == 2:
    matriz_retorno = np.zeros((2,3))
    for i in range(matriz.shape[0]):
      for j in range(matriz.shape[1]):
        matriz_retorno[i][j] = matriz[i][j] + ((matriz_1[i][j]*2)-1)
    return matriz_retorno
  else:
    matriz_retorno = np.zeros((3))
    for i in range(matriz.shape[0]):
      matriz_retorno[i] = matriz[i] + ((matriz_2[i]*2)-1)
    return matriz_retorno

In [ ]:
def atualizar_array(matriz_1, matriz_2):
  if matriz_1.shape[0] == 2:
    for i in range(matriz_1.shape[0]):
      for j in range(matriz_1.shape[1]):
        matriz_1[i][j] = matriz_2[i][j] 
  else:
    for i in range(matriz_1.shape[0]):
      matriz_1[i] = matriz_2[i]


In [ ]:
w1 = np.random.rand(2,3)
w2 = np.random.rand(3)
manipular_peso_trash_hold(w1)
manipular_peso_trash_hold(w2)
I = np.zeros((3,3))
O = np.zeros((3,3))
for i in range(len(E1)):
  #I1 - copia dos dados de entrada.
  I[0][0] = E1[i]
  I[0][1] = E2[i]
  I[0][2] = 1.0 # Constante.
  #Copia para os Outputs
  O[0][0] = I[0][0]
  O[0][1] = I[0][1]
  O[0][2] = I[0][2]
  #Calculo Para as entradas da segunda camada.
  I[1][0] = O[0][0]*w1[0][0] + O[0][1]*w1[0][1] + O[0][2]*w1[0][2]
  I[1][1] = O[0][0]*w1[1][0] + O[0][1]*w1[1][1] + O[0][2]*w1[1][2]
  I[1][2] = 1.0 # constante.
  #Calculo do Exp para trash_hold.
  O[1][0] = 1.0/(1.0+np.exp(-I[1][0]))
  O[1][1] = 1.0/(1.0+np.exp(-I[1][1]))
  O[1][2] = I[1][2]
  #calculo da ultima entrada
  I[2][0] = O[1][0]*w2[0] + O[1][1]*w2[1] + O[1][2]*w2[2]
  #Calculo da ultima saida
  O[2][0] = 1.0/(1.0+np.exp(-I[2][0]))
  erro_inicial += float(pow((saida[i]-O[2][0]),2))
erro_inicial *= 0.5
peso_comparar_1 = []
peso_comparar_2 = []
peso_comparar_3 = []
for i in range(w1.shape[1]):
  peso_comparar_1.append(w1[0][i])
  peso_comparar_2.append(w1[1][i])
  peso_comparar_3.append(w2[i])
print(erro_inicial)
print(w1)
print(w2)

0.8434547709949677
[[-14.92120668  18.66871354  -9.58095977]
 [ 15.88946097  -4.93001135  -6.55113023]]
[ -1.94494118  13.61020333 -15.07591423]


In [ ]:
erro = 1.0
n = 0.0
while erro > tx:
  diferenca_erro = 0.0
  erro = 0.0
  saidas = []
  w1_copia = passo(w1)
  w2_copia = passo(w2)
  #print(w1_copia)
  #print(w2_copia)
  #print('----------------')
  I = np.zeros((3,3))
  O = np.zeros((3,3))
  for i in range(len(E1)):
    #I1 - copia dos dados de entrada.
    I[0][0] = E1[i]
    I[0][1] = E2[i]
    I[0][2] = 1.0 # Constante.
    #Copia para os Outputs
    O[0][0] = I[0][0]
    O[0][1] = I[0][1]
    O[0][2] = I[0][2]
    #Calculo Para as entradas da segunda camada.
    I[1][0] = O[0][0]*w1_copia[0][0] + O[0][1]*w1_copia[0][1] + O[0][2]*w1_copia[0][2]
    I[1][1] = O[0][0]*w1_copia[1][0] + O[0][1]*w1_copia[1][1] + O[0][2]*w1_copia[1][2]
    I[1][2] = 1.0 # constante.
    #Calculo do Exp para trash_hold.
    O[1][0] = 1.0/(1.0+np.exp(-I[1][0]))
    O[1][1] = 1.0/(1.0+np.exp(-I[1][1]))
    O[1][2] = I[1][2]
    #calculo da ultima entrada
    I[2][0] = O[1][0]*w2_copia[0] + O[1][1]*w2_copia[1] + O[1][2]*w2_copia[2]
    #Calculo da ultima saida
    O[2][0] = 1.0/(1.0+np.exp(-I[2][0]))
    erro +=  (saida[i]-O[2][0]) * (saida[i]-O[2][0])
    saidas.append(round(O[2][0]))
  n+=1
  erro *= 0.5
  diferenca_erro = erro - erro_inicial
  if diferenca_erro < 0.0:
    #print(diferenca_erro)
    atualizar_array(w1, w1_copia)
    atualizar_array(w2, w2_copia)
    erro_inicial = erro
    if erro < tx:
      break
  else:
    #print('if')
    sorteio = np.random.rand()
    #print(sorteio)
    exponencial = (np.exp(-diferenca_erro))/KT
    #print(exponencial)
    #print('-----------------')
    if exponencial > sorteio:
      #print('Atualizar array')
      atualizar_array(w1, w1_copia)
      atualizar_array(w2, w2_copia)
      erro_inicial = erro
      if erro < tx:
        break



In [ ]:

print("Epoca: " + str(n))
print("Erro: " + str(erro))
peso1 = []
peso2 = []
peso3 = []
for i in range(w1.shape[1]):
  peso1.append(w1[0][i])
  peso2.append(w1[1][i])
  peso3.append(w2[i])
df_1['W0_inicial'] = peso_comparar_1
df_1['W0_final'] = peso1
df_1['W1_inicial'] = peso_comparar_2
df_1['W1_final'] = peso2
df_1['W2_inicial'] = peso_comparar_3
df_1['W2_final'] = peso3


df_1

Epoca: 18142.0
Erro: 6.624229952748489e-06


W0_inicial   W0_final  W1_inicial   W1_final  W2_inicial    W2_final
0  -14.921207  32.790719   15.889461 -49.688322   -1.944941   22.610801
1   18.668714 -45.881218   -4.930011  30.351097   13.610203  159.709549
2   -9.580960 -31.431745   -6.551130 -31.971295  -15.075914  -12.376824

In [ ]:
df['E1'] = E1
df['E2'] = E2
df['Saidas_esperadas'] = saida
df['Saidas_geradas'] = saidas
df

E1  E2  Saidas_esperadas  Saidas_geradas
0   0   0               0.0               0
1   0   1               1.0               1
2   1   0               1.0               1
3   1   1               0.0               0

In [ ]:
print(saidas)

[0, 1, 1, 0]
